<?php

namespace Container3cDHZyT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RCFZk6hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RCFZk6h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RCFZk6h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.QVAk1vM.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\ReservationController::index' => ['privates', '.service_locator.25wzWUF.App\\Controller\\ReservationController::index()', 'getReservationControllerindexService', true],
            'App\\Controller\\ReservationController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ReservationController::new()', 'getReservationControllernewService', true],
            'App\\Controller\\ReservationController::show' => ['privates', '.service_locator.GRHR7ox.App\\Controller\\ReservationController::show()', 'getReservationControllershowService', true],
            'App\\Controller\\ReservationController::edit' => ['privates', '.service_locator.Apz.94I.App\\Controller\\ReservationController::edit()', 'getReservationControllereditService', true],
            'App\\Controller\\ReservationController::delete' => ['privates', '.service_locator.Apz.94I.App\\Controller\\ReservationController::delete()', 'getReservationControllerdeleteService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.QVAk1vM.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\ReservationController:index' => ['privates', '.service_locator.25wzWUF.App\\Controller\\ReservationController::index()', 'getReservationControllerindexService', true],
            'App\\Controller\\ReservationController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ReservationController::new()', 'getReservationControllernewService', true],
            'App\\Controller\\ReservationController:show' => ['privates', '.service_locator.GRHR7ox.App\\Controller\\ReservationController::show()', 'getReservationControllershowService', true],
            'App\\Controller\\ReservationController:edit' => ['privates', '.service_locator.Apz.94I.App\\Controller\\ReservationController::edit()', 'getReservationControllereditService', true],
            'App\\Controller\\ReservationController:delete' => ['privates', '.service_locator.Apz.94I.App\\Controller\\ReservationController::delete()', 'getReservationControllerdeleteService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ReservationController::index' => '?',
            'App\\Controller\\ReservationController::new' => '?',
            'App\\Controller\\ReservationController::show' => '?',
            'App\\Controller\\ReservationController::edit' => '?',
            'App\\Controller\\ReservationController::delete' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ReservationController:index' => '?',
            'App\\Controller\\ReservationController:new' => '?',
            'App\\Controller\\ReservationController:show' => '?',
            'App\\Controller\\ReservationController:edit' => '?',
            'App\\Controller\\ReservationController:delete' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
