<?php

namespace ContainerEYKBhpi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RYELumOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rYELumO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rYELumO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.QVAk1vM.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\ReservationController::index' => ['privates', '.service_locator.25wzWUF.App\\Controller\\ReservationController::index()', 'getReservationControllerindexService', true],
            'App\\Controller\\ReservationController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ReservationController::new()', 'getReservationControllernewService', true],
            'App\\Controller\\ReservationController::show' => ['privates', '.service_locator.GRHR7ox.App\\Controller\\ReservationController::show()', 'getReservationControllershowService', true],
            'App\\Controller\\ReservationController::edit' => ['privates', '.service_locator.Apz.94I.App\\Controller\\ReservationController::edit()', 'getReservationControllereditService', true],
            'App\\Controller\\ReservationController::delete' => ['privates', '.service_locator.Apz.94I.App\\Controller\\ReservationController::delete()', 'getReservationControllerdeleteService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\TypeBilletController::index' => ['privates', '.service_locator.MfWGcK3.App\\Controller\\TypeBilletController::index()', 'getTypeBilletControllerindexService', true],
            'App\\Controller\\TypeBilletController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\TypeBilletController::new()', 'getTypeBilletControllernewService', true],
            'App\\Controller\\TypeBilletController::show' => ['privates', '.service_locator.q9rJgpS.App\\Controller\\TypeBilletController::show()', 'getTypeBilletControllershowService', true],
            'App\\Controller\\TypeBilletController::edit' => ['privates', '.service_locator.D9yy3cj.App\\Controller\\TypeBilletController::edit()', 'getTypeBilletControllereditService', true],
            'App\\Controller\\TypeBilletController::delete' => ['privates', '.service_locator.D9yy3cj.App\\Controller\\TypeBilletController::delete()', 'getTypeBilletControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.QVAk1vM.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\ReservationController:index' => ['privates', '.service_locator.25wzWUF.App\\Controller\\ReservationController::index()', 'getReservationControllerindexService', true],
            'App\\Controller\\ReservationController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\ReservationController::new()', 'getReservationControllernewService', true],
            'App\\Controller\\ReservationController:show' => ['privates', '.service_locator.GRHR7ox.App\\Controller\\ReservationController::show()', 'getReservationControllershowService', true],
            'App\\Controller\\ReservationController:edit' => ['privates', '.service_locator.Apz.94I.App\\Controller\\ReservationController::edit()', 'getReservationControllereditService', true],
            'App\\Controller\\ReservationController:delete' => ['privates', '.service_locator.Apz.94I.App\\Controller\\ReservationController::delete()', 'getReservationControllerdeleteService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.mXDaS5b.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\TypeBilletController:index' => ['privates', '.service_locator.MfWGcK3.App\\Controller\\TypeBilletController::index()', 'getTypeBilletControllerindexService', true],
            'App\\Controller\\TypeBilletController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\TypeBilletController::new()', 'getTypeBilletControllernewService', true],
            'App\\Controller\\TypeBilletController:show' => ['privates', '.service_locator.q9rJgpS.App\\Controller\\TypeBilletController::show()', 'getTypeBilletControllershowService', true],
            'App\\Controller\\TypeBilletController:edit' => ['privates', '.service_locator.D9yy3cj.App\\Controller\\TypeBilletController::edit()', 'getTypeBilletControllereditService', true],
            'App\\Controller\\TypeBilletController:delete' => ['privates', '.service_locator.D9yy3cj.App\\Controller\\TypeBilletController::delete()', 'getTypeBilletControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ReservationController::index' => '?',
            'App\\Controller\\ReservationController::new' => '?',
            'App\\Controller\\ReservationController::show' => '?',
            'App\\Controller\\ReservationController::edit' => '?',
            'App\\Controller\\ReservationController::delete' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\TypeBilletController::index' => '?',
            'App\\Controller\\TypeBilletController::new' => '?',
            'App\\Controller\\TypeBilletController::show' => '?',
            'App\\Controller\\TypeBilletController::edit' => '?',
            'App\\Controller\\TypeBilletController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ReservationController:index' => '?',
            'App\\Controller\\ReservationController:new' => '?',
            'App\\Controller\\ReservationController:show' => '?',
            'App\\Controller\\ReservationController:edit' => '?',
            'App\\Controller\\ReservationController:delete' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\TypeBilletController:index' => '?',
            'App\\Controller\\TypeBilletController:new' => '?',
            'App\\Controller\\TypeBilletController:show' => '?',
            'App\\Controller\\TypeBilletController:edit' => '?',
            'App\\Controller\\TypeBilletController:delete' => '?',
        ]);
    }
}
