<?php

namespace ContainerEYKBhpi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeBilletControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q9rJgpS.App\Controller\TypeBilletController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q9rJgpS.App\\Controller\\TypeBilletController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'typeBillet' => ['privates', '.errored..service_locator.q9rJgpS.App\\Entity\\TypeBillet', NULL, 'Cannot autowire service ".service_locator.q9rJgpS": it needs an instance of "App\\Entity\\TypeBillet" but this type has been excluded in "config/services.yaml".'],
        ], [
            'typeBillet' => 'App\\Entity\\TypeBillet',
        ]))->withContext('App\\Controller\\TypeBilletController::show()', $container);
    }
}
