<?php

namespace ContainerEYKBhpi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeBilletControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D9yy3cj.App\Controller\TypeBilletController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D9yy3cj.App\\Controller\\TypeBilletController::delete()'] = ($container->privates['.service_locator.D9yy3cj'] ?? $container->load('get_ServiceLocator_D9yy3cjService'))->withContext('App\\Controller\\TypeBilletController::delete()', $container);
    }
}
