<?php

namespace ContainerEYKBhpi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeBillet2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.q9rJgpS.App\Entity\TypeBillet' shared service.
     *
     * @return \App\Entity\TypeBillet
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.q9rJgpS": it needs an instance of "App\\Entity\\TypeBillet" but this type has been excluded in "config/services.yaml".');
    }
}
