<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEYKBhpi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEYKBhpi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEYKBhpi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEYKBhpi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEYKBhpi\App_KernelDevDebugContainer([
    'container.build_hash' => 'EYKBhpi',
    'container.build_id' => 'cf82d890',
    'container.build_time' => 1729944618,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEYKBhpi');
